version: "3.9"
services:
  influxdb:
    hostname: paros-influxdb
    container_name: paros-influxdb
    image: influxdb:2.5.1
    network_mode: "host"
    environment:
      - INFLUXD_STORAGE_CACHE_MAX_MEMORY_SIZE=2000000000
    volumes:
      - /mnt/paros-influxdb-data:/var/lib/influxdb2
  grafana:
    hostname: paros-grafana
    container_name: paros-grafana
    image: grafana/grafana-oss
    network_mode: "host"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
    volumes:
      - /mnt/paros-grafana-data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
  prometheus:
    hostname: paros-prometheus
    image: prom/prometheus
    network_mode: "host"
    user: 1002:1002
    volumes:
      - ./prometheus:/etc/prometheus
      - /mnt/paros-prometheus-data:/prometheus
